enum productActionTypes {
  SHOW_LOADING = "SHOW_LOADING",
  HIDE_LOADING = "HIDE_LOADING",
  REQUEST_PRODUCTS_SAGA = "REQUEST_PRODUCTS_SAGA",
  SET_PRODUCTS = "SET_PRODUCTS",
  SET_SORT = "SET_SORT",
  SET_SIZE = "SET_SIZE",
  ADD_TO_CART = "ADD_TO_CART",
  DEL_FROM_CART = "DEL_FROM_CART",
  UPDATE_CART = "UPDATE_CART",
}

export default productActionTypes;
